require("config.keymaps.general")
require("config.keymaps.lazy")
require("config.keymaps.nvim-tree")
-- Telescope keymaps are now defined in lua/plugins/telescope.lua
require("config.keymaps.themes")
require("config.keymaps.mason")
require("config.keymaps.lsp")
require("config.keymaps.noice")
require("config.keymaps.mini")
require("config.keymaps.bufferline")
require("config.keymaps.trouble")